### ISSUE TITLE
How to set readtimeout for a query in cassandra-co?

### ISSUE THREAD

**Issue by mjmanav4** [kunalgolani/cassandra-co#9]
We can set timeout option while using cassandra driver .Check The following link https://docs.datastax.com/en/developer/nodejs-driver/3.1/api/type.ClientOptions/
 ```
var cassandra = require('cassandra-driver');
     module.exports = new cassandra.Client({ contactPoints: 
     localhost, keyspace: 'mydb', 
     socketOptions: { readTimeout: 200 } });
```
but how do we specify timeout for cassandra-co client? @kunalgolani 
There is no variable called readTimeout in SocketOptions object for cassandra-co client?
https://docs.datastax.com/en/drivers/nodejs/2.0/global.html#QueryOptions

**Comment by kunalgolani** [comment]
You can pass custom `ClientOptions` at Instantiation: https://github.com/kunalgolani/cassandra-co#instantiation

The docs there point to `v2.0` of the driver, but `cassandra-co` has been upgraded to `v3.0`.

Please reopen the issue if this doesn't help.

**Comment by mjmanav4** [comment]
so is this the correct way to define cassandraClient with timeout:
`cassandraClient = require('cassandra-co')('keyspace', localhost, {socketOptions: { readTimeout: 200 }  });`

**Comment by kunalgolani** [comment]
`localhost` should be in an array, but the rest looks good. The third argument is just passed on to the driver.

**Comment by mjmanav4** [comment]
var db = require('cassandra-co')('mydb', [ '127.0.0.1' ], { socketOptions: { readTimeout: 200 } });
 console.log(db.socketOptions); //undefined

**Comment by mjmanav4** [comment]
` var cdb = require('cassandra-co')('lgp', [ '127.0.0.1' ], { socketOptions: { readTimeout: 200 } });
// console.log(cdb.adapter.client.options.socketOptions);

function *get() {


    var Emp = yield cdb.getModel('emp');
    console.log(Emp);
    /*
     var x = new Emp({
        emp_id: 123,
        emp_name: 'mj',
        emp_city: 'bangalore',
        emp_sal: 123,
        emp_phone: 123
    }).save();
    */
  var x = yield Emp.find();
  console.log(x);

}
var x = get();
console.log(x.next());
console.log(x.next());
`

gives error : { value: {}, done: false }
Cannot read property 'find' of undefined

**Comment by kunalgolani** [comment]
That's not enough detail to go on. What did those console logs give you? Is `db` really the keyspace?
